version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: "/admin-js/"
    schedule:
      interval: daily
    groups:
      react-admin:
        patterns:
          - "create-react-admin"
          - "ra-*"
          - "react-admin"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
