codecov:
  notify:
    after_n_builds: 3
flag_management:
  individual_flags:
    - name: unit
      paths: 
        - "aiohttp_admin/"
        - "tests/"
    - name: integration
      paths: 
        - "admin-js/src/"
        - "admin-js/tests/"
        - "aiohttp_admin/"
        - "examples/"
